### ISSUE TITLE
"failed to send organization invitation to user", but invited members received invitation.

### ISSUE THREAD

**Issue by dskst** [askul/actions-github-organizer#31]
Invite for 16 members, I received error. 
```
2020-03-31 01:40:01.116 ERROR -  failure: failed to send organization invitation to user[account name], due to: RequestError [HttpError]
    at /home/runner/work/_actions/askul/actions-github-organizer/v1/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async Promise.all (index 26) {
  name: 'HttpError',
  status: 500,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '0',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 31 Mar 2020 01:40:01 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '500 Internal Server Error',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'admin:org',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '***',
    'x-oauth-scopes': 'admin:org, public_repo, workflow',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4856',
    'x-ratelimit-reset': '1585622285',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/orgs/***/invitations',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.39.0 Node.js/12.13.1 (Linux 5.0; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"invitee_id":***,"role":"direct_member"}',
    request: { hook: [Function: bound bound register], validate: [Object] }
  }
}
```
This error confirmed at all invited members.

But, all invited members received invitation.

**Comment by ryoKkk** [comment]
same as #4, fixed in https://github.com/askul/actions-github-organizer/pull/24

**Comment by dskst** [comment]
Thank you for your reply. Issue is closed.
